AWSTemplateFormatVersion: '2010-09-09'
Description: 'Baseline Secrets Manager entries for external integrations'

Parameters:
  Brand:
    Type: String
    Default: marsmen
    Description: 'Brand identifier to prefix secret names'

  Environment:
    Type: String
    Default: prod
    Description: 'Environment label (dev/stage/prod) used for tagging'

  CreateStripeSecrets:
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'false'
    Description: 'Set to true if Stripe secrets should be provisioned'

Conditions:
  IncludeStripe: !Equals [!Ref CreateStripeSecrets, 'true']

Resources:
  ShopifyAdminApiSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${Brand}/shopify/admin-api'
      Description: 'Shopify Admin API access token (SecretString.access_token)'
      SecretString: '{"access_token":""}'
      Tags:
        - Key: Brand
          Value: !Ref Brand
        - Key: Environment
          Value: !Ref Environment

  RechargeWebhookSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${Brand}/recharge/webhook'
      Description: 'Recharge webhook signing secret (SecretString.webhook_secret)'
      SecretString: '{"webhook_secret":""}'
      Tags:
        - Key: Brand
          Value: !Ref Brand
        - Key: Environment
          Value: !Ref Environment

  StripeApiSecret:
    Type: AWS::SecretsManager::Secret
    Condition: IncludeStripe
    Properties:
      Name: !Sub '${Brand}/stripe/api'
      Description: 'Stripe API key (SecretString.api_key)'
      SecretString: '{"api_key":"","webhook_secret":""}'
      Tags:
        - Key: Brand
          Value: !Ref Brand
        - Key: Environment
          Value: !Ref Environment

Outputs:
  ShopifyAdminApiSecretArn:
    Description: 'ARN for the Shopify Admin API secret'
    Value: !Ref ShopifyAdminApiSecret
  RechargeWebhookSecretArn:
    Description: 'ARN for the Recharge webhook secret'
    Value: !Ref RechargeWebhookSecret
  StripeApiSecretArn:
    Condition: IncludeStripe
    Description: 'ARN for the Stripe API secret (if created)'
    Value: !Ref StripeApiSecret
